webtalk_init -webtalk_dir C:/Users/silvi/workspace/tfe4141_term_project/edit_rsa_accelerator/edit_rsa_accelerator.sim/sim_1/behav/xsim/xsim.dir/rsa_core_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 23 15:34:34 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8310c52d-db3a-4ef9-8515-959eea37f015" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "91b9267eb12847098834f19c071e9069" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "42 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 527379311 -regid "" -xml C:/Users/silvi/workspace/tfe4141_term_project/edit_rsa_accelerator/edit_rsa_accelerator.sim/sim_1/behav/xsim/xsim.dir/rsa_core_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/silvi/workspace/tfe4141_term_project/edit_rsa_accelerator/edit_rsa_accelerator.sim/sim_1/behav/xsim/xsim.dir/rsa_core_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/silvi/workspace/tfe4141_term_project/edit_rsa_accelerator/edit_rsa_accelerator.sim/sim_1/behav/xsim/xsim.dir/rsa_core_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
