# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rsa_soc/rsa_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc || ORIG_REF_NAME==rsa_soc} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_processing_system7_0_0/rsa_soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_processing_system7_0_0 || ORIG_REF_NAME==rsa_soc_processing_system7_0_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_axi_dma_0_0/rsa_soc_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_axi_dma_0_0 || ORIG_REF_NAME==rsa_soc_axi_dma_0_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_axi_smc_0/rsa_soc_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_axi_smc_0 || ORIG_REF_NAME==rsa_soc_axi_smc_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_rst_ps7_0_100M_0/rsa_soc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==rsa_soc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_ps7_0_axi_periph_0/rsa_soc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==rsa_soc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_xbar_0/rsa_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_xbar_0 || ORIG_REF_NAME==rsa_soc_xbar_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_rsa_accelerator_0_0/rsa_soc_rsa_accelerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_accelerator_0_0 || ORIG_REF_NAME==rsa_soc_rsa_accelerator_0_0} -quiet] -quiet

# IP: bd/rsa_soc/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_auto_pc_0 || ORIG_REF_NAME==rsa_soc_auto_pc_0} -quiet] -quiet

# XDC: bd/rsa_soc/rsa_soc_ooc.xdc
